version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.13.3
    working_directory: ~/repo

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            black --check src/gettysparqlpatterns

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test_requirements.txt
            pip install .
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint:
          context: GETTY
      - test:
          context: GETTY